import { AppContextProvider } from '@/utils/appContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body >{children}</body>
      </html>
    </AppContextProvider>
  )
}
